color: null
description: null
fieldLayouts:
  acee04fe-7aba-4a24-9c47-de16f73cc4a2:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-07-07T15:39:35+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 69c3f5ac-014f-4f64-9af1-bb369028c37e # obj
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e27dd2c0-d02c-4991-a7bb-92a7ce847593
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-07T15:39:35+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 67053669-973b-4b91-b703-67ee8097172e # gens
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f18ebf75-167c-42b5-89f0-f56f62e455be
            userCondition: null
            warning: null
            width: 100
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-07-08T19:47:32+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 8ac8c47c-9f55-4bb3-a121-68886eeee80d
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 5e347eb0-0b4d-441a-a48c-1d02a7ad94a8
        userCondition: null
handle: active
hasTitleField: true
icon: null
name: active
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
