color: null
description: null
fieldLayouts:
  1dbe5e1b-97f5-4199-8f7b-e2e66c3b1a1f:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-07-24T17:52:07+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: d539b172-afae-4ac8-9be7-66b540702c16
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-24T17:53:26+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 67053669-973b-4b91-b703-67ee8097172e # gens
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c6d57de2-f501-43cb-9973-77f0c9c54b16
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 2971f183-9c72-45ca-9e3a-e34e491c0ba3
        userCondition: null
handle: agenda
hasTitleField: true
icon: null
name: agenda
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
