color: null
fieldLayouts:
  c6628142-dc50-4013-b846-77bc07fc4280:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-05-13T23:58:16+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: ea18b754-04d8-455b-bf41-a404e114976a
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-14T16:42:53+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 69c3f5ac-014f-4f64-9af1-bb369028c37e # obj
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5a1dccfb-ec03-4797-a13e-176a96c88daf
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-14T16:42:53+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 69c3f5ac-014f-4f64-9af1-bb369028c37e # obj
            handle: obj2
            includeInCards: false
            instructions: null
            label: obj2
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 699bae6d-e6c4-4764-a635-a7a22c5393c0
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-15T01:24:47+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 67053669-973b-4b91-b703-67ee8097172e # gens
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 11ebfa29-4902-4f3b-9cae-14b2d4ce6e0d
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 71ae5e4c-5fb1-433a-a649-2f870bcfe0b7
        userCondition: null
handle: anno
hasTitleField: true
icon: null
name: anno
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
