color: null
description: null
fieldLayouts:
  056ce236-b470-4712-8288-b7688627a8fc:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-08-02T21:07:57+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 6430cb98-76c5-458e-ab58-9dfbe6fc189e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-08-02T21:09:52+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 67053669-973b-4b91-b703-67ee8097172e # gens
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5f46628d-706d-440b-8c77-c59193676da1
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-08-02T21:09:52+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 69c3f5ac-014f-4f64-9af1-bb369028c37e # obj
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3eb8d835-1f09-469c-8ef4-175e546e9190
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 1e9a2a71-c716-4032-a866-edb5b43b4aec
        userCondition: null
handle: compaidant
hasTitleField: true
icon: null
name: compaidant
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
