color: null
description: null
fieldLayouts:
  4d6645cc-d689-43e4-b1f9-e8c6278781a7:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-07-30T22:17:53+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 4d9ed064-bbb3-4464-9c5f-ecc44cb01f82
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-30T22:20:08+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 1e97a057-af73-48f8-80e0-184566f52a11 # date
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 92f5f08a-26b5-4ebb-89ba-1197bf92d1a6
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-30T22:20:08+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 69c3f5ac-014f-4f64-9af1-bb369028c37e # obj
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 72e5f4e9-7dfb-49ac-8b4e-d405085ab412
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-30T22:21:27+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 67053669-973b-4b91-b703-67ee8097172e # gens
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2c9fc8a7-8e6f-494e-ac53-bc6e3cb24c25
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 9b0978a8-4be9-4ec8-b97c-d6a9c7ad88d8
        userCondition: null
handle: deadline
hasTitleField: true
icon: null
name: deadline
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
