color: null
fieldLayouts:
  a83d1083-41fb-40b8-b770-f2ff45e01eb2:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-05-13T23:42:21+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 70a8daad-ead2-4f94-ac52-030335293235
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-13T23:44:11+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 67053669-973b-4b91-b703-67ee8097172e # gens
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2ce574ef-6ce3-4069-b60d-5986f40565a6
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-13T23:44:53+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: dd47950a-e2dc-4e5d-b507-006a2629150a # etape
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dbda8704-17f4-430e-adf1-939831f196ad
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 33348e02-b7af-49e6-8e9d-c420a3389612
        userCondition: null
handle: etape
hasTitleField: true
icon: null
name: etape
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
