color: null
description: null
fieldLayouts:
  2639e97b-5c39-43ef-8f05-cbde58ec1ba0:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-07-24T18:50:18+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 9d4bcffe-d5de-4749-8a90-a48eb4a8d218
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-24T18:51:38+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: e352bde4-e3c9-49ca-9794-0c9af2c3da2c # tagg
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a3d2de73-fe9b-4d71-bbf2-d168eab1e2ba
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-24T18:51:38+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 67053669-973b-4b91-b703-67ee8097172e # gens
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7d15752d-bf0c-40a9-9b04-2e1fa3246396
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-24T18:52:47+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 1f2c85dc-5cd1-4832-a32e-4c60d5535d27 # dt
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d8a8ea9c-38b0-4715-a34f-4a2c09617744
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 0050de79-345b-4091-95d2-58299bc64c39
        userCondition: null
handle: genstag
hasTitleField: true
icon: null
name: genstag
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
