color: null
description: null
fieldLayouts:
  72b271a7-acab-49b4-b189-1ac305ed8463:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-07-28T18:41:23+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: aa13bba9-1e37-437f-bb40-71780cf4edf8
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-28T18:44:01+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 67053669-973b-4b91-b703-67ee8097172e # gens
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e63e1e40-f1d3-466b-8965-9c6b293120c2
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-28T18:44:01+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 67053669-973b-4b91-b703-67ee8097172e # gens
            handle: groupe
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c14813e8-f7d0-4e13-a94b-b1874792b573
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 6433bb0a-b1da-42d0-b454-2968f14507c3
        userCondition: null
handle: groupeinvitated
hasTitleField: true
icon: null
name: groupeinvitated
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
