color: null
fieldLayouts:
  3a14ae55-0aba-46ec-ad10-f0abf0c9cf00:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-05-13T23:47:27+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 91584d79-89c8-44bd-a3a1-4c1ecbe9557c
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-13T23:49:16+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 9c9f6981-8090-489f-8538-a1951cc17589 # img
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ec0b4331-9191-4397-89de-2797e5b7a7fb
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-13T23:49:16+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 67053669-973b-4b91-b703-67ee8097172e # gens
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c42f8372-0c8d-4297-acbc-7b35601f84c4
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-13T23:49:16+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 69c3f5ac-014f-4f64-9af1-bb369028c37e # obj
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cc70ce96-11b6-482b-815f-814fb773fdd1
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: aca380e3-05e2-4951-8526-d9acafc05a40
        userCondition: null
handle: img
hasTitleField: true
icon: null
name: img
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
