color: null
fieldLayouts:
  65b827fd-3b56-4c63-9704-eb3ffe83f4d4:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-06-22T10:44:07+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 7fd57216-cd48-4412-92ea-1e2bae8a2fea
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-06-22T10:47:43+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 67053669-973b-4b91-b703-67ee8097172e # gens
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ca012d4a-8777-41df-a400-7edff365e9ad
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-06-22T12:05:44+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 75770ca1-8311-4f39-81c8-20e99b9bb03f # versionmoment
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9eb15279-ccd1-4d9e-84fb-455ca604e747
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: ba27f7b2-e59a-4eb4-b143-7994559408dc
        userCondition: null
handle: note
hasTitleField: true
icon: null
name: note
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
