color: null
description: null
fieldLayouts:
  b8392049-98f9-4b43-bf14-69707a5b21e6:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-07-26T04:21:35+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 63051c98-6b19-4479-953e-7e762c1e92f2
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-26T04:23:37+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 69c3f5ac-014f-4f64-9af1-bb369028c37e # obj
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3e89e43a-d274-4779-8ffc-73aa8d0cce26
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-26T04:23:37+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 67053669-973b-4b91-b703-67ee8097172e # gens
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 749ca3a2-8722-493a-8062-3f4ccf4495c8
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-26T04:25:05+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: c3a81b8b-98ea-40b0-b2e5-37f85ba24937 # valence
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a36a30e2-49ed-4f15-b7e8-ecef7ac214d8
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 49e16e26-308b-4169-afb6-d0b620772f11
        userCondition: null
handle: vot
hasTitleField: true
icon: null
name: vot
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
