defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 8dba8da5-80a5-4037-8275-09211e173f1f # alert
handle: alert
maxAuthors: 1
name: alert
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  b30a01d7-c759-48e9-8f48-21317d371ddc: # a
    enabledByDefault: true
    hasUrls: true
    template: alert/_entry.twig
    uriFormat: 'alert/{slug}'
type: channel
