defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 5e91ed90-f5e3-4aa8-9423-61a37bb77917 # anno
handle: anno
maxAuthors: 1
name: anno
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  b30a01d7-c759-48e9-8f48-21317d371ddc: # a
    enabledByDefault: true
    hasUrls: true
    template: anno/_entry.twig
    uriFormat: 'anno/{slug}'
type: channel
