defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 293ffd56-b277-41a3-8301-cac69c3b584e # arttag
handle: arttag
maxAuthors: 1
name: arttag
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  b30a01d7-c759-48e9-8f48-21317d371ddc: # a
    enabledByDefault: true
    hasUrls: true
    template: arttag/_entry.twig
    uriFormat: 'arttag/{slug}'
type: channel
