defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: a6fd3d62-1ce1-4231-b404-a4197ec7b048 # artvers
handle: artvers
maxAuthors: 1
name: Artvers
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  b30a01d7-c759-48e9-8f48-21317d371ddc: # a
    enabledByDefault: true
    hasUrls: true
    template: artvers/_entry.twig
    uriFormat: 'artvers/{slug}'
type: channel
