defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: fbafa0b2-bb9a-480e-b1c4-c609bd0aa8c4 # competence
handle: competence
maxAuthors: 1
name: Competence
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  b30a01d7-c759-48e9-8f48-21317d371ddc: # a
    enabledByDefault: true
    hasUrls: true
    template: competence/_entry.twig
    uriFormat: 'competence/{slug}'
type: channel
