defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 4f24ce8b-3261-40e5-8aca-a05d3bccaf60 # etape
handle: etape
maxAuthors: 1
name: etape
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  b30a01d7-c759-48e9-8f48-21317d371ddc: # a
    enabledByDefault: true
    hasUrls: true
    template: etape/_entry.twig
    uriFormat: 'etape/{slug}'
type: channel
