defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 184e9cf2-7ee6-4f12-8061-7857317e846b # img
handle: img
maxAuthors: 1
name: img
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  b30a01d7-c759-48e9-8f48-21317d371ddc: # a
    enabledByDefault: true
    hasUrls: true
    template: img/_entry.twig
    uriFormat: 'img/{slug}'
type: channel
