defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: aaa18eea-f177-476e-bdac-282240f23be7 # moment
handle: moment
maxAuthors: 1
name: moment
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  b30a01d7-c759-48e9-8f48-21317d371ddc: # a
    enabledByDefault: true
    hasUrls: true
    template: moment/_entry.twig
    uriFormat: 'moment/{slug}'
type: channel
