defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: b4ce6bb9-4b2f-494a-a3f9-372cd84da076 # role
handle: role
maxAuthors: 1
name: role
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  b30a01d7-c759-48e9-8f48-21317d371ddc: # a
    enabledByDefault: true
    hasUrls: true
    template: role/_entry.twig
    uriFormat: 'role/{slug}'
type: channel
