defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: e79726c5-a736-483f-a2f6-9fb057f93870 # valide
handle: valide
maxAuthors: 1
name: Valide
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  b30a01d7-c759-48e9-8f48-21317d371ddc: # a
    enabledByDefault: true
    hasUrls: true
    template: valide/_entry.twig
    uriFormat: 'valide/{slug}'
type: channel
