defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: a62216ec-f89c-455f-ae05-0b38ece91f3a # version
handle: version
maxAuthors: 1
name: Version
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  b30a01d7-c759-48e9-8f48-21317d371ddc: # a
    enabledByDefault: true
    hasUrls: true
    template: version/_entry.twig
    uriFormat: 'version/{slug}'
type: channel
