columnSuffix: null
handle: date
instructions: null
name: date
searchable: false
settings:
  max: null
  min: null
  minuteIncrement: 60
  showDate: true
  showTime: true
  showTimeZone: false
translationKeyFormat: null
translationMethod: none
type: craft\fields\Date
