columnSuffix: null
handle: valence
instructions: null
name: valence
searchable: false
settings:
  decimals: 0
  defaultValue: null
  max: 2
  min: 0
  prefix: null
  previewCurrency: null
  previewFormat: decimal
  size: null
  step: null
  suffix: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
