dateModified: 1747181951
email:
  fromEmail: az@gmail.com
  fromName: a
  transportType: craft\mail\transportadapters\Sendmail
fs:
  imgs:
    hasUrls: true
    name: imgs
    settings:
      path: $DOCUMENT_ROOT/imgs
    type: craft\fs\Local
    url: $PRIMARY_SITE_URL/imgs
meta:
  __names__:
    2dddfe37-8a4c-4b9b-9571-b01263c8747d: img # img
    3c5ed36b-c006-4f27-8b03-fc8650ea8a17: gens # gens
    4f24ce8b-3261-40e5-8aca-a05d3bccaf60: etape # etape
    5e91ed90-f5e3-4aa8-9423-61a37bb77917: anno # anno
    8dba8da5-80a5-4037-8275-09211e173f1f: alert # alert
    9c9f6981-8090-489f-8538-a1951cc17589: img # img
    9c632554-a190-480a-a78e-ad96ba997b07: pass # pass
    24f213a4-a991-4525-bca3-2df7a8363c59: mail # mail
    69c3f5ac-014f-4f64-9af1-bb369028c37e: obj # obj
    78d55181-c699-49ed-b79c-f5ebc485e8a0: desc # desc
    184e9cf2-7ee6-4f12-8061-7857317e846b: img # img
    262fd559-19c4-4ceb-9bfa-9c751e02f956: phone # phone
    318fcb02-663c-4be2-90f0-2b1bfe73a7c7: vote # vote
    994fb679-4658-4e19-ab52-b452a3e5ff05: userole # userole
    4269450f-fd7c-46a8-a8bd-e3de97e45a4b: abo # abo
    6040607e-af45-4ff2-a846-f600ab7d159f: vote # vote
    67053669-973b-4b91-b703-67ee8097172e: gens # gens
    69783038-459d-47e1-8b2b-ec799a371a3c: a # a
    acf2011f-27b9-42d7-a21b-8d1501ade2f8: imgsvol # imgsvol
    ae4cfa98-5b15-4613-b8c9-67459f28d815: tag # tag
    b4ce6bb9-4b2f-494a-a3f9-372cd84da076: role # role
    b30a01d7-c759-48e9-8f48-21317d371ddc: a # a
    c89a4029-d853-4c39-b675-224ad9decd9a: role # role
    cfdea3fe-70d2-49e7-aded-a86ea2b3a5f5: desc # desc
    d8a4ec52-c969-4c7f-8e51-64ffd33f5eb9: gens # gens
    d2855a8a-5c35-417b-b805-0c265b314bbf: alert # alert
    d722116d-af1a-4bab-be40-011270cb86ae: abo # abo
    dd47950a-e2dc-4e5d-b507-006a2629150a: etape # etape
    e526d7b1-2116-4739-a365-e2788f483864: etape # etape
    fc5f9eb4-f7b5-4b15-b4f8-40734fe2c56e: anno # anno
plugins:
  guest-entries:
    edition: standard
    enabled: true
    schemaVersion: 2.1.0
    settings:
      enableCsrfProtection: '1'
      entryVariable: entry
      sections:
        __assoc__:
          -
            - 4269450f-fd7c-46a8-a8bd-e3de97e45a4b # abo
            -
              __assoc__:
                -
                  - sectionUid
                  - 4269450f-fd7c-46a8-a8bd-e3de97e45a4b # abo
                -
                  - allowGuestSubmissions
                  - '1'
                -
                  - enabledByDefault
                  - '1'
                -
                  - runValidation
                  - '1'
                -
                  - authorUid
                  - 6aedeb60-106d-4680-a70b-e765c2765d75
          -
            - d2855a8a-5c35-417b-b805-0c265b314bbf # alert
            -
              __assoc__:
                -
                  - sectionUid
                  - d2855a8a-5c35-417b-b805-0c265b314bbf # alert
                -
                  - allowGuestSubmissions
                  - '1'
                -
                  - enabledByDefault
                  - '1'
                -
                  - runValidation
                  - '1'
                -
                  - authorUid
                  - 6aedeb60-106d-4680-a70b-e765c2765d75
          -
            - fc5f9eb4-f7b5-4b15-b4f8-40734fe2c56e # anno
            -
              __assoc__:
                -
                  - sectionUid
                  - fc5f9eb4-f7b5-4b15-b4f8-40734fe2c56e # anno
                -
                  - allowGuestSubmissions
                  - '1'
                -
                  - enabledByDefault
                  - '1'
                -
                  - runValidation
                  - '1'
                -
                  - authorUid
                  - 6aedeb60-106d-4680-a70b-e765c2765d75
          -
            - 78d55181-c699-49ed-b79c-f5ebc485e8a0 # desc
            -
              __assoc__:
                -
                  - sectionUid
                  - 78d55181-c699-49ed-b79c-f5ebc485e8a0 # desc
                -
                  - allowGuestSubmissions
                  - '1'
                -
                  - enabledByDefault
                  - '1'
                -
                  - runValidation
                  - '1'
                -
                  - authorUid
                  - 6aedeb60-106d-4680-a70b-e765c2765d75
          -
            - e526d7b1-2116-4739-a365-e2788f483864 # etape
            -
              __assoc__:
                -
                  - sectionUid
                  - e526d7b1-2116-4739-a365-e2788f483864 # etape
                -
                  - allowGuestSubmissions
                  - '1'
                -
                  - enabledByDefault
                  - '1'
                -
                  - runValidation
                  - '1'
                -
                  - authorUid
                  - 6aedeb60-106d-4680-a70b-e765c2765d75
          -
            - d8a4ec52-c969-4c7f-8e51-64ffd33f5eb9 # gens
            -
              __assoc__:
                -
                  - sectionUid
                  - d8a4ec52-c969-4c7f-8e51-64ffd33f5eb9 # gens
                -
                  - allowGuestSubmissions
                  - '1'
                -
                  - enabledByDefault
                  - '1'
                -
                  - runValidation
                  - '1'
                -
                  - authorUid
                  - 6aedeb60-106d-4680-a70b-e765c2765d75
          -
            - 2dddfe37-8a4c-4b9b-9571-b01263c8747d # img
            -
              __assoc__:
                -
                  - sectionUid
                  - 2dddfe37-8a4c-4b9b-9571-b01263c8747d # img
                -
                  - allowGuestSubmissions
                  - '1'
                -
                  - enabledByDefault
                  - '1'
                -
                  - runValidation
                  - '1'
                -
                  - authorUid
                  - 6aedeb60-106d-4680-a70b-e765c2765d75
          -
            - c89a4029-d853-4c39-b675-224ad9decd9a # role
            -
              __assoc__:
                -
                  - sectionUid
                  - c89a4029-d853-4c39-b675-224ad9decd9a # role
                -
                  - allowGuestSubmissions
                  - '1'
                -
                  - enabledByDefault
                  - '1'
                -
                  - runValidation
                  - '1'
                -
                  - authorUid
                  - 6aedeb60-106d-4680-a70b-e765c2765d75
          -
            - 6040607e-af45-4ff2-a846-f600ab7d159f # vote
            -
              __assoc__:
                -
                  - sectionUid
                  - 6040607e-af45-4ff2-a846-f600ab7d159f # vote
                -
                  - allowGuestSubmissions
                  - '1'
                -
                  - enabledByDefault
                  - '1'
                -
                  - runValidation
                  - '1'
                -
                  - authorUid
                  - 6aedeb60-106d-4680-a70b-e765c2765d75
system:
  edition: solo
  live: true
  name: a
  schemaVersion: 5.7.0.3
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
