dateModified: 1752095917
email:
  fromEmail: az@gmail.com
  fromName: a
  transportType: craft\mail\transportadapters\Sendmail
fs:
  imgs:
    hasUrls: true
    name: imgs
    settings:
      path: $DOCUMENT_ROOT/imgs
    type: craft\fs\Local
    url: $PRIMARY_SITE_URL/imgs
meta:
  __names__:
    1f2c85dc-5cd1-4832-a32e-4c60d5535d27: dt # dt
    3c5ed36b-c006-4f27-8b03-fc8650ea8a17: gens # gens
    4a5d9ad2-7db0-4763-b109-a7a2e264d13d: note # note
    4ddf2db2-8cc7-4ae8-8f6a-48121be92459: active # active
    4f24ce8b-3261-40e5-8aca-a05d3bccaf60: etape # etape
    5e91ed90-f5e3-4aa8-9423-61a37bb77917: anno # anno
    07c9bcb9-821e-40fc-87b7-600d07df1385: real # real
    7df43cfb-822b-4393-9cea-f95c274c89bd: lieu # lieu
    8af7f98b-7a5f-473f-a84f-4ce5ccb86560: tagg # tagg
    8dba8da5-80a5-4037-8275-09211e173f1f: alert # alert
    9c9f6981-8090-489f-8538-a1951cc17589: img # img
    9c83564b-daca-48c5-b427-99f12a40d4d2: image # image
    9c632554-a190-480a-a78e-ad96ba997b07: pass # pass
    24f213a4-a991-4525-bca3-2df7a8363c59: mail # mail
    31c9f996-5cd8-4e53-bee4-a5b67a4d54f1: 'Public Schema' # Public Schema
    63d5e9c8-1466-486f-859a-fc37eb6e2a5b: image # image
    69c3f5ac-014f-4f64-9af1-bb369028c37e: obj # obj
    184e9cf2-7ee6-4f12-8061-7857317e846b: img # img
    221a2b9b-2b23-4323-9fd7-c62512c41c97: moment # moment
    262fd559-19c4-4ceb-9bfa-9c751e02f956: phone # phone
    304cd698-b2e5-461c-a9f0-10c849c2acd3: active # active
    306dff20-c17b-4130-a8e4-6a9fad9bbf99: voyage # voyage
    318fcb02-663c-4be2-90f0-2b1bfe73a7c7: vote # vote
    380e1fd7-f86c-4a02-8444-9c55021cbd37: voyage # voyage
    973cf1c7-299c-4b63-a065-6dd23ea7314b: zone # zone
    994fb679-4658-4e19-ab52-b452a3e5ff05: userole # userole
    3589b5bf-6fb3-43bb-8294-37d78c659f0b: version # version
    4718b1b0-6cbc-46c1-a42f-40ba14078b4c: caracteristique # caracteristique
    75770ca1-8311-4f39-81c8-20e99b9bb03f: versionmoment # versionmoment
    438474b0-8857-43a4-8e54-c3ae4dcda3bc: tagg # tagg
    67053669-973b-4b91-b703-67ee8097172e: gens # gens
    69783038-459d-47e1-8b2b-ec799a371a3c: a # a
    a290bbdd-6af4-4850-aabb-b9fbdc2cf25d: texte # texte
    a62216ec-f89c-455f-ae05-0b38ece91f3a: version # version
    aaa18eea-f177-476e-bdac-282240f23be7: moment # moment
    acf2011f-27b9-42d7-a21b-8d1501ade2f8: imgsvol # imgsvol
    ae4cfa98-5b15-4613-b8c9-67459f28d815: tag # tag
    b4ce6bb9-4b2f-494a-a3f9-372cd84da076: role # role
    b30a01d7-c759-48e9-8f48-21317d371ddc: a # a
    bc6f2f8d-e16b-4597-9283-5b0a7f078ffe: caracteristique # caracteristique
    cfdea3fe-70d2-49e7-aded-a86ea2b3a5f5: desc # desc
    d7c18dfa-8aad-4879-9efa-fe8b1a1dea2f: caracteristique # caracteristique
    d8a4ec52-c969-4c7f-8e51-64ffd33f5eb9: gens # gens
    d722116d-af1a-4bab-be40-011270cb86ae: abo # abo
    dd47950a-e2dc-4e5d-b507-006a2629150a: etape # etape
    e352bde4-e3c9-49ca-9794-0c9af2c3da2c: tagg # tagg
    ec4d61c5-22ab-448d-ae33-fefa9e004994: versionmoment # versionmoment
    edd5eb1b-ad48-4b1b-b88a-fda3189bce72: guuumod # guuumod
    f1017c71-c97e-4d79-84ba-5f9cde6dfd5d: texte # texte
plugins:
  guest-entries:
    edition: standard
    enabled: true
    schemaVersion: 2.1.0
    settings:
      enableCsrfProtection: '1'
      entryVariable: entry
      sections:
        __assoc__:
          -
            - 4269450f-fd7c-46a8-a8bd-e3de97e45a4b
            -
              __assoc__:
                -
                  - sectionUid
                  - 4269450f-fd7c-46a8-a8bd-e3de97e45a4b
                -
                  - allowGuestSubmissions
                  - '1'
                -
                  - enabledByDefault
                  - '1'
                -
                  - runValidation
                  - '1'
                -
                  - authorUid
                  - 6aedeb60-106d-4680-a70b-e765c2765d75
          -
            - d2855a8a-5c35-417b-b805-0c265b314bbf
            -
              __assoc__:
                -
                  - sectionUid
                  - d2855a8a-5c35-417b-b805-0c265b314bbf
                -
                  - allowGuestSubmissions
                  - '1'
                -
                  - enabledByDefault
                  - '1'
                -
                  - runValidation
                  - '1'
                -
                  - authorUid
                  - 6aedeb60-106d-4680-a70b-e765c2765d75
          -
            - fc5f9eb4-f7b5-4b15-b4f8-40734fe2c56e
            -
              __assoc__:
                -
                  - sectionUid
                  - fc5f9eb4-f7b5-4b15-b4f8-40734fe2c56e
                -
                  - allowGuestSubmissions
                  - '1'
                -
                  - enabledByDefault
                  - '1'
                -
                  - runValidation
                  - '1'
                -
                  - authorUid
                  - 6aedeb60-106d-4680-a70b-e765c2765d75
          -
            - 78d55181-c699-49ed-b79c-f5ebc485e8a0
            -
              __assoc__:
                -
                  - sectionUid
                  - 78d55181-c699-49ed-b79c-f5ebc485e8a0
                -
                  - allowGuestSubmissions
                  - '1'
                -
                  - enabledByDefault
                  - '1'
                -
                  - runValidation
                  - '1'
                -
                  - authorUid
                  - 6aedeb60-106d-4680-a70b-e765c2765d75
          -
            - e526d7b1-2116-4739-a365-e2788f483864
            -
              __assoc__:
                -
                  - sectionUid
                  - e526d7b1-2116-4739-a365-e2788f483864
                -
                  - allowGuestSubmissions
                  - '1'
                -
                  - enabledByDefault
                  - '1'
                -
                  - runValidation
                  - '1'
                -
                  - authorUid
                  - 6aedeb60-106d-4680-a70b-e765c2765d75
          -
            - d8a4ec52-c969-4c7f-8e51-64ffd33f5eb9 # gens
            -
              __assoc__:
                -
                  - sectionUid
                  - d8a4ec52-c969-4c7f-8e51-64ffd33f5eb9 # gens
                -
                  - allowGuestSubmissions
                  - '1'
                -
                  - enabledByDefault
                  - '1'
                -
                  - runValidation
                  - '1'
                -
                  - authorUid
                  - 0f378e12-6438-4246-853e-3f21d474d87b
          -
            - 2dddfe37-8a4c-4b9b-9571-b01263c8747d
            -
              __assoc__:
                -
                  - sectionUid
                  - 2dddfe37-8a4c-4b9b-9571-b01263c8747d
                -
                  - allowGuestSubmissions
                  - '1'
                -
                  - enabledByDefault
                  - '1'
                -
                  - runValidation
                  - '1'
                -
                  - authorUid
                  - 6aedeb60-106d-4680-a70b-e765c2765d75
          -
            - c89a4029-d853-4c39-b675-224ad9decd9a
            -
              __assoc__:
                -
                  - sectionUid
                  - c89a4029-d853-4c39-b675-224ad9decd9a
                -
                  - allowGuestSubmissions
                  - '1'
                -
                  - enabledByDefault
                  - '1'
                -
                  - runValidation
                  - '1'
                -
                  - authorUid
                  - 6aedeb60-106d-4680-a70b-e765c2765d75
          -
            - 6040607e-af45-4ff2-a846-f600ab7d159f
            -
              __assoc__:
                -
                  - sectionUid
                  - 6040607e-af45-4ff2-a846-f600ab7d159f
                -
                  - allowGuestSubmissions
                  - '1'
                -
                  - enabledByDefault
                  - '1'
                -
                  - runValidation
                  - '1'
                -
                  - authorUid
                  - 6aedeb60-106d-4680-a70b-e765c2765d75
          -
            - 42451543-abcb-4cf1-8051-f71d3999f379
            -
              __assoc__:
                -
                  - sectionUid
                  - 42451543-abcb-4cf1-8051-f71d3999f379
                -
                  - allowGuestSubmissions
                  - '1'
                -
                  - enabledByDefault
                  - '1'
                -
                  - runValidation
                  - '1'
                -
                  - authorUid
                  - 6aedeb60-106d-4680-a70b-e765c2765d75
          -
            - 109c879d-6651-4af3-82d5-c40e884515f0
            -
              __assoc__:
                -
                  - sectionUid
                  - 109c879d-6651-4af3-82d5-c40e884515f0
                -
                  - allowGuestSubmissions
                  - '1'
                -
                  - enabledByDefault
                  - '1'
                -
                  - runValidation
                  - '1'
                -
                  - authorUid
                  - 6aedeb60-106d-4680-a70b-e765c2765d75
          -
            - 63d5e9c8-1466-486f-859a-fc37eb6e2a5b # image
            -
              __assoc__:
                -
                  - sectionUid
                  - 63d5e9c8-1466-486f-859a-fc37eb6e2a5b # image
                -
                  - allowGuestSubmissions
                  - '1'
                -
                  - enabledByDefault
                  - '1'
                -
                  - runValidation
                  - '1'
                -
                  - authorUid
                  - 0f378e12-6438-4246-853e-3f21d474d87b
          -
            - 65a653aa-888c-47ec-8f68-7c85bf874a46
            -
              __assoc__:
                -
                  - sectionUid
                  - 65a653aa-888c-47ec-8f68-7c85bf874a46
                -
                  - allowGuestSubmissions
                  - '1'
                -
                  - enabledByDefault
                  - '1'
                -
                  - runValidation
                  - '1'
                -
                  - authorUid
                  - 0f378e12-6438-4246-853e-3f21d474d87b
          -
            - 1fee50f0-5560-42b0-afa6-b7a7183eebd8
            -
              __assoc__:
                -
                  - sectionUid
                  - 1fee50f0-5560-42b0-afa6-b7a7183eebd8
                -
                  - allowGuestSubmissions
                  - '1'
                -
                  - enabledByDefault
                  - '1'
                -
                  - runValidation
                  - '1'
                -
                  - authorUid
                  - 0f378e12-6438-4246-853e-3f21d474d87b
          -
            - a3732d22-9a25-4d2c-92d6-e9d37f1dc0b7
            -
              __assoc__:
                -
                  - sectionUid
                  - a3732d22-9a25-4d2c-92d6-e9d37f1dc0b7
                -
                  - allowGuestSubmissions
                  - '1'
                -
                  - enabledByDefault
                  - '1'
                -
                  - runValidation
                  - '1'
                -
                  - authorUid
                  - 0f378e12-6438-4246-853e-3f21d474d87b
          -
            - aeba1fc8-271e-46b8-bc9c-c2362a048adc
            -
              __assoc__:
                -
                  - sectionUid
                  - aeba1fc8-271e-46b8-bc9c-c2362a048adc
                -
                  - allowGuestSubmissions
                  - '1'
                -
                  - enabledByDefault
                  - '1'
                -
                  - runValidation
                  - '1'
                -
                  - authorUid
                  - 0f378e12-6438-4246-853e-3f21d474d87b
          -
            - d7c18dfa-8aad-4879-9efa-fe8b1a1dea2f # caracteristique
            -
              __assoc__:
                -
                  - sectionUid
                  - d7c18dfa-8aad-4879-9efa-fe8b1a1dea2f # caracteristique
                -
                  - allowGuestSubmissions
                  - '1'
                -
                  - enabledByDefault
                  - '1'
                -
                  - runValidation
                  - '1'
                -
                  - authorUid
                  - 0f378e12-6438-4246-853e-3f21d474d87b
          -
            - 8af7f98b-7a5f-473f-a84f-4ce5ccb86560 # tagg
            -
              __assoc__:
                -
                  - sectionUid
                  - 8af7f98b-7a5f-473f-a84f-4ce5ccb86560 # tagg
                -
                  - allowGuestSubmissions
                  - '1'
                -
                  - enabledByDefault
                  - '1'
                -
                  - runValidation
                  - '1'
                -
                  - authorUid
                  - 0f378e12-6438-4246-853e-3f21d474d87b
          -
            - f1017c71-c97e-4d79-84ba-5f9cde6dfd5d # texte
            -
              __assoc__:
                -
                  - sectionUid
                  - f1017c71-c97e-4d79-84ba-5f9cde6dfd5d # texte
                -
                  - allowGuestSubmissions
                  - '1'
                -
                  - enabledByDefault
                  - '1'
                -
                  - runValidation
                  - '1'
                -
                  - authorUid
                  - 0f378e12-6438-4246-853e-3f21d474d87b
          -
            - 3589b5bf-6fb3-43bb-8294-37d78c659f0b # version
            -
              __assoc__:
                -
                  - sectionUid
                  - 3589b5bf-6fb3-43bb-8294-37d78c659f0b # version
                -
                  - allowGuestSubmissions
                  - '1'
                -
                  - enabledByDefault
                  - '1'
                -
                  - runValidation
                  - '1'
                -
                  - authorUid
                  - 0f378e12-6438-4246-853e-3f21d474d87b
          -
            - 4ddf2db2-8cc7-4ae8-8f6a-48121be92459 # active
            -
              __assoc__:
                -
                  - sectionUid
                  - 4ddf2db2-8cc7-4ae8-8f6a-48121be92459 # active
                -
                  - allowGuestSubmissions
                  - '1'
                -
                  - enabledByDefault
                  - '1'
                -
                  - runValidation
                  - '1'
                -
                  - authorUid
                  - 0f378e12-6438-4246-853e-3f21d474d87b
system:
  edition: solo
  live: true
  name: a
  schemaVersion: 5.8.0.3
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
