altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  82f0a2e2-6862-4bd4-8b74-08aa43900864:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-05-13T23:50:57+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: c190b0af-2556-4ccd-8f73-f7f2e0c5a325
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 046bce52-4949-476a-8f03-3b20fed37713
        userCondition: null
fs: imgs
handle: imgsvol
name: imgsvol
sortOrder: 1
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
